"""Bulk Salary Structure Assignment for every active employee.

Reuses the existing well-built `Staff` Salary Structure (DSPL) which has:
  Earnings: Basic & DA, HRA, Medical, LTA, Conveyance, Children Education,
            Food, Statutory Bonus, Special Allowance (balancer)
  Deductions: PF (12% capped @ 1800), ESIC (0.75% if base ≤ 21k),
              PT (gender + month-aware India formula)

Clones it once for DCEPL → `DCEPL Staff` so DCEPL employees can be
assigned without violating the company filter.

Per-employee base CTC resolution:
  1. TALLY_BASES — 22 employees with Salary Advance pattern in Tally
     vouchers (last 3 months avg). Rough proxy — usually within ±20%.
  2. DESIGNATION_BAND — typical India payroll bands for the rest.
  3. DEFAULT_BASE — last-resort 20k fallback.

Operations - DCEPL operators get a placeholder base too — they're paid
mostly through Operator Logsheet Pay (Phase 2.4 Additional Salary)
but still need an SSA so they appear in payroll cycles.

Skips Directors (handled via Remuneration to Directors, not payroll).

User explicitly chose this Tally-derived approach knowing values will
need cleanup ("B and i will clean up in erpnext itself"). The CTCs
below are best-effort starting points — HR cleans up on the desk.

Usage:
    bench --site dgoc.logstop.com execute vaishali.setup_salary_structure.run
"""
import frappe
from frappe import _

DSPL = "Dynamic Servitech Private Limited"
DCEPL = "Dynamic Crane Engineers Private Limited"

DSPL_STRUCTURE = "Staff"
DCEPL_STRUCTURE = "DCEPL Staff"

# FY 26-27 effective date
EFFECTIVE_FROM = "2026-04-01"

# Tally-derived avg monthly salary (advance disbursements, last 3 months
# of FY 25-26). Generated by parsing voucher_entries.json from
# ~/ers/data/tally/{dcepl2,dspl}/. Names are normalised (lowercase,
# no staff IDs, no suffixes like "salary advance").
TALLY_BASES = {
    "aniket deshmukh":       75000,
    "ansari illyas":         20000,
    "ashok misal":           10000,
    "avhad ramdas":          50000,
    "bhupal singh":           5700,
    "hasbullah shaikh":       6500,
    "mahesh pandhare":       12500,
    "md khalique anjum":     60000,
    "mohd hasbullah shaikh": 10000,
    "nagesh omprakash lohar": 6250,
    "neha marotrao kadam":    5000,
    "pooja shinde":          50000,
    "pranav kumar":          10000,
    "rajkumar prajapati":     5000,
    "ram kumar kushwaha":     5000,
    "sambhaji sonawale":     10000,
    "sharwan prajapati":      7500,
    "shubham tupe":          20000,
    "vikas babu":             5000,
    "vitthal salekar":       21500,
    "yogendra gautam":        5000,
}

# Designation band fallback — India payroll typical ranges for the
# Dynamic Group's roles. Refine on the desk per individual.
DESIGNATION_BAND = {
    "MANAGING DIRECTOR": 0,            # skip (director's remuneration)
    "DIRECTOR": 0,
    "CHAIRPERSON": 0,

    "MANAGER-SERVICE": 60000,
    "ASSISTANT MANAGER-MAINTENANCE": 45000,
    "ASSISTANT MANAGER": 45000,
    "MANAGER": 60000,
    "SR. MANAGER": 80000,

    "EXECUTIVE BUSINESS DEVELOPMENT": 35000,
    "BUSINESS DEVELOPMENT EXECUTIVE": 35000,
    "BUSINESS DEVELOPMENT MANAGER": 50000,

    "SR. SERVICE ENGINEER": 40000,
    "SERVICE ENGINEER": 28000,
    "TR. SERVICE ENGINEER": 18000,

    "SR. MECHANIC": 30000,
    "MECHANIC": 22000,
    "JR. MECHANIC": 18000,

    "ELECTRICAL TECHNICIAN": 22000,
    "SERVICE TECHNICIAN": 22000,

    "DRIVER": 18000,
    "OPERATOR": 18000,                 # rental crane operators
    "CRANE OPERATOR": 18000,

    "EXECUTIVE STORES & PURCHASE": 25000,
    "EXECUTIVE-STORES & PURCHASE": 25000,
    "STORE EXECUTIVE": 22000,
    "STORE-KEEPER": 18000,

    "ACCOUNTS EXECUTIVE": 25000,
    "ACCOUNTS MANAGER": 50000,
    "ACCOUNTS HEAD": 70000,

    "HR EXECUTIVE": 25000,
    "HR MANAGER": 50000,

    "PURCHASE EXECUTIVE": 25000,
    "PURCHASE MANAGER": 50000,
    "SALES EXECUTIVE": 28000,
    "SALES MANAGER": 60000,
    "MARKETING EXECUTIVE": 25000,
}

DEFAULT_BASE = 20000

DIRECTOR_DESIGNATIONS = {"MANAGING DIRECTOR", "DIRECTOR", "CHAIRPERSON"}


def run():
    print("\n=== Salary Structure setup ===\n")
    _ensure_dcepl_structure()
    frappe.db.commit()
    counts = _bulk_assign()
    frappe.db.commit()
    print(f"\n✓ Done. {counts}\n")


# ── Salary Structure cloning ──────────────────────────────────────

def _ensure_dcepl_structure():
    """Clone the existing DSPL `Staff` Salary Structure into `DCEPL Staff`
    with identical components and formulas — only the company link
    differs. Idempotent."""
    if frappe.db.exists("Salary Structure", DCEPL_STRUCTURE):
        existing = frappe.db.get_value("Salary Structure", DCEPL_STRUCTURE,
                                       ["company", "is_active", "docstatus"], as_dict=True)
        if existing and existing.docstatus == 1 and existing.is_active == "Yes":
            print(f"  Salary Structure: {DCEPL_STRUCTURE} already submitted")
            return
        frappe.delete_doc("Salary Structure", DCEPL_STRUCTURE,
                          ignore_permissions=True, force=True)

    src = frappe.get_doc("Salary Structure", DSPL_STRUCTURE)
    new = frappe.copy_doc(src)
    new.name = None
    new.salary_structure_name = DCEPL_STRUCTURE
    new.company = DCEPL
    new.is_active = "Yes"
    new.insert(ignore_permissions=True)
    new.submit()
    print(f"  Salary Structure: created {DCEPL_STRUCTURE} (cloned from {DSPL_STRUCTURE})")


# ── Bulk Salary Structure Assignment ──────────────────────────────

def _bulk_assign():
    employees = frappe.get_all(
        "Employee",
        filters={"status": "Active"},
        fields=["name", "employee_name", "company", "designation", "department"],
    )

    structure_for = {DSPL: DSPL_STRUCTURE, DCEPL: DCEPL_STRUCTURE}

    counts = {"created": 0, "already_assigned": 0,
              "directors_skipped": 0, "errors": 0,
              "from_tally": 0, "from_band": 0, "from_default": 0}

    for emp in employees:
        designation = (emp.designation or "").upper().strip()
        if designation in DIRECTOR_DESIGNATIONS:
            counts["directors_skipped"] += 1
            continue

        # Skip if employee already has any submitted SSA
        if frappe.db.exists("Salary Structure Assignment",
                            {"employee": emp.name, "docstatus": 1}):
            counts["already_assigned"] += 1
            continue

        structure = structure_for.get(emp.company)
        if not structure:
            counts["errors"] += 1
            frappe.log_error(f"No structure mapped for company {emp.company} (emp {emp.name})",
                             "SalaryStructure")
            continue

        base, source = _resolve_base(emp.employee_name, designation)
        counts[f"from_{source}"] += 1

        try:
            ssa = frappe.new_doc("Salary Structure Assignment")
            ssa.employee = emp.name
            ssa.salary_structure = structure
            ssa.from_date = EFFECTIVE_FROM
            ssa.base = base
            ssa.company = emp.company
            ssa.insert(ignore_permissions=True)
            ssa.submit()
            counts["created"] += 1
            if counts["created"] % 25 == 0:
                frappe.db.commit()
                print(f"  … {counts['created']} assignments committed")
        except Exception as e:
            counts["errors"] += 1
            frappe.log_error(
                f"SSA failed for {emp.name} ({emp.employee_name}): {str(e)[:200]}",
                "SalaryStructure",
            )

    return counts


# ── Base resolution ───────────────────────────────────────────────

def _resolve_base(employee_name, designation_upper):
    """Returns (base_amount_inr, source) where source ∈ {tally, band, default}."""
    name_norm = (employee_name or "").lower()

    # Tally pass — token-overlap match, requires ≥2 shared tokens
    name_tokens = set(name_norm.replace(".", " ").split())
    for tally_name, base in TALLY_BASES.items():
        tally_tokens = set(tally_name.split())
        shared = name_tokens & tally_tokens
        # Require both first and last name to overlap, OR strong overlap
        if len(shared) >= 2:
            return base, "tally"

    # Designation band
    if designation_upper in DESIGNATION_BAND:
        b = DESIGNATION_BAND[designation_upper]
        if b > 0:
            return b, "band"

    return DEFAULT_BASE, "default"
