"""Bulk Salary Structure Assignment for every active employee.

Reuses the existing well-built `Staff` Salary Structure (DSPL) which has:
  Earnings: Basic & DA, HRA, Medical, LTA, Conveyance, Children Education,
            Food, Statutory Bonus, Special Allowance (balancer)
  Deductions: PF (12% capped @ 1800), ESIC (0.75% if base ≤ 21k),
              PT (gender + month-aware India formula)

Clones it once for DCEPL → `DCEPL Staff` so DCEPL employees can be
assigned without violating the company filter.

Per-employee base CTC resolution:
  1. TALLY_BASES — 22 employees with Salary Advance pattern in Tally
     vouchers (last 3 months avg). Rough proxy — usually within ±20%.
  2. DESIGNATION_BAND — typical India payroll bands for the rest.
  3. DEFAULT_BASE — last-resort 20k fallback.

Operations - DCEPL operators get a placeholder base too — they're paid
mostly through Operator Logsheet Pay (Phase 2.4 Additional Salary)
but still need an SSA so they appear in payroll cycles.

Skips Directors (handled via Remuneration to Directors, not payroll).

User explicitly chose this Tally-derived approach knowing values will
need cleanup ("B and i will clean up in erpnext itself"). The CTCs
below are best-effort starting points — HR cleans up on the desk.

Usage:
    bench --site dgoc.logstop.com execute vaishali.setup_salary_structure.run
"""
import frappe
from frappe import _

DSPL = "Dynamic Servitech Private Limited"
DCEPL = "Dynamic Crane Engineers Private Limited"

DSPL_STRUCTURE = "Staff"
DCEPL_STRUCTURE = "DCEPL Staff"

# FY 26-27 effective date
EFFECTIVE_FROM = "2026-04-01"

# Bank-statement-derived avg monthly salary (top-3 months of NEFT/IMPS
# debits per recipient, FY 25-26). Generated by parsing
# ~/ers/data/bankstatements/bank.db (DCEPL HDFC + DSPL ICICI/TJSB +
# DCEPL ICICI 24-25), then fuzzy-matched to active ERPNext employees.
# Keys are the exact ERPNext Employee.employee_name strings.
BANK_BASES = {
    "AKSHAY BARAKU SHINDE":               29936,
    "AMOL CHINTAMAN SATPUTE":             10000,
    "AMZAD . ALI":                        17744,
    "ANIKET VASANTRAO DESHMUKH":          25000,
    "ANJOR VASANT GANVIR":                22766,
    "ANKITA VARUN BIRADAR":               13078,
    "BHARTI NITIN GOKHALE":              135000,  # director — separate path
    "BHUPAL CHANDRA SINGH":               10000,
    "DEEPAK TULJIRAM TANGADE":            41667,
    "DIGVIJAY KINNU PRASAD GUPTA":        13010,
    "DINESH RAMESHWAR ADEY":              15108,
    "DNYANESHWAR SATISH ZINGE":           54506,
    "DNYANESHWAR VISHNU CHAVAN":          16667,
    "HARSHWARDHAN NITIN GOKHALE":         69236,  # director — separate path
    "JABIR HABIB SHAIKH":                 15389,
    "KALIDAS SAHEBRAO VANSHIV":           10000,
    "MD INZAMAMUL Haque":                 41600,
    "MD MOBIN NISAR AHMAD ASHRAF":         8000,
    "MOHD HASBULLAH . SHAIKH":            15000,
    "MUKUNDA BHAGU AKHADE":               14000,
    "NIRANJAN RAJESHWAR SINGH KUMAR":     22518,
    "NITIN JAYANT GOKHALE":              138085,  # director — separate path
    "POOJA NARAYAN SHINDE":               50000,
    "PRANAV PANKAJ KUMAR":                15000,
    "PRATIK ASHOKRAO DESHMUKH":           36678,
    "PRATIK BHAGAVAN PATIL":              57087,
    "RAGHUVIR SHRINIWAS JOSHI":           47298,
    "RAJENDRA NATHU KUDALE":              86667,
    "RAJNISH KUMAR NANHAKU RAM BHARTI":   90000,
    "RAVIRAJ BABAN DHAINJE":              10894,
    "SAGAR SHIVAGOUDA KORE":              22833,
    "SAHIL VINOD SHINDE":                 11403,
    "SAMBHAJI SADASHIV SONAWALE":         20000,
    "SHARWAN JAGDISH PRAJAPATI":          10000,
    "SURAJ RAJENDRA DIVEKAR":             20000,
    "SURAJ UPENDRA JAYASAWAL":            42720,
    "SUSHANT SURESH SHINDE":              25000,
    "UMASHANKAR A. BISHNUKESH DORA":      15000,
    "VIJAY KUMAR GOND":                   16000,
    "VINAY . KUMAR":                     200000,
    "VISHAL LDNYANESHWAR WAGHMARE":       39771,
    "VISHAL SANJAYRAO DESHPANDE":         20000,
    "VISHVAS POPAT AHER":                 15389,
    "VISHWAJIT SUNIL JAGTAP":             31840,  # associate director
    "VITTHAL DASHRATH SALEKAR":            8000,
}

# Designation band fallback — India payroll typical ranges for the
# Dynamic Group's roles. Refine on the desk per individual.
DESIGNATION_BAND = {
    "MANAGING DIRECTOR": 0,            # skip (director's remuneration)
    "DIRECTOR": 0,
    "CHAIRPERSON": 0,

    "MANAGER-SERVICE": 60000,
    "ASSISTANT MANAGER-MAINTENANCE": 45000,
    "ASSISTANT MANAGER": 45000,
    "MANAGER": 60000,
    "SR. MANAGER": 80000,

    "EXECUTIVE BUSINESS DEVELOPMENT": 35000,
    "BUSINESS DEVELOPMENT EXECUTIVE": 35000,
    "BUSINESS DEVELOPMENT MANAGER": 50000,

    "SR. SERVICE ENGINEER": 40000,
    "SERVICE ENGINEER": 28000,
    "TR. SERVICE ENGINEER": 18000,

    "SR. MECHANIC": 30000,
    "MECHANIC": 22000,
    "JR. MECHANIC": 18000,

    "ELECTRICAL TECHNICIAN": 22000,
    "SERVICE TECHNICIAN": 22000,

    "DRIVER": 18000,
    "OPERATOR": 18000,                 # rental crane operators
    "CRANE OPERATOR": 18000,

    "EXECUTIVE STORES & PURCHASE": 25000,
    "EXECUTIVE-STORES & PURCHASE": 25000,
    "STORE EXECUTIVE": 22000,
    "STORE-KEEPER": 18000,

    "ACCOUNTS EXECUTIVE": 25000,
    "ACCOUNTS MANAGER": 50000,
    "ACCOUNTS HEAD": 70000,

    "HR EXECUTIVE": 25000,
    "HR MANAGER": 50000,

    "PURCHASE EXECUTIVE": 25000,
    "PURCHASE MANAGER": 50000,
    "SALES EXECUTIVE": 28000,
    "SALES MANAGER": 60000,
    "MARKETING EXECUTIVE": 25000,
}

DEFAULT_BASE = 20000

# Designations that get Director's Remuneration, NOT a regular salary
# structure. Plural and "Associate Director" included.
DIRECTOR_DESIGNATIONS = {
    "MANAGING DIRECTOR", "DIRECTOR", "DIRECTORS", "CHAIRPERSON",
    "ASSOCIATE DIRECTOR", "EXECUTIVE DIRECTOR", "WHOLE TIME DIRECTOR",
}


def run(force_update=0):
    """Run the bulk assignment.

    Pass force_update=1 to cancel existing submitted SSAs first and
    re-create with the latest BANK_BASES + designation bands. Use this
    after refreshing the bank-extracted data."""
    print("\n=== Salary Structure setup ===\n")
    _ensure_dcepl_structure()
    frappe.db.commit()
    if int(force_update):
        cancelled = _cancel_existing_ssas()
        print(f"  force_update: cancelled {cancelled} existing SSA(s)\n")
    counts = _bulk_assign()
    frappe.db.commit()
    print(f"\n✓ Done. {counts}\n")


def _cancel_existing_ssas():
    """Cancel every submitted Salary Structure Assignment so the next
    bulk pass can recreate them with fresh bases. Director SSAs are
    cancelled too (we'll skip them on recreate)."""
    submitted = frappe.get_all("Salary Structure Assignment",
        filters={"docstatus": 1}, pluck="name")
    cancelled = 0
    for name in submitted:
        try:
            doc = frappe.get_doc("Salary Structure Assignment", name)
            doc.cancel()
            cancelled += 1
        except Exception as e:
            frappe.log_error(f"Cancel SSA {name} failed: {e}", "SalaryCancel")
    frappe.db.commit()
    return cancelled


# ── Salary Structure cloning ──────────────────────────────────────

def _ensure_dcepl_structure():
    """Clone the existing DSPL `Staff` Salary Structure into `DCEPL Staff`
    with identical components and formulas — only the company link
    differs. Idempotent."""
    if frappe.db.exists("Salary Structure", DCEPL_STRUCTURE):
        existing = frappe.db.get_value("Salary Structure", DCEPL_STRUCTURE,
                                       ["company", "is_active", "docstatus"], as_dict=True)
        if existing and existing.docstatus == 1 and existing.is_active == "Yes":
            print(f"  Salary Structure: {DCEPL_STRUCTURE} already submitted")
            return
        frappe.delete_doc("Salary Structure", DCEPL_STRUCTURE,
                          ignore_permissions=True, force=True)

    src = frappe.get_doc("Salary Structure", DSPL_STRUCTURE)
    new = frappe.copy_doc(src)
    # autoname='prompt' on Salary Structure — must set name explicitly
    new.name = DCEPL_STRUCTURE
    new.salary_structure_name = DCEPL_STRUCTURE
    new.company = DCEPL
    new.is_active = "Yes"
    new.flags.name_set = True
    new.insert(ignore_permissions=True, set_name=DCEPL_STRUCTURE)
    new.submit()
    print(f"  Salary Structure: created {DCEPL_STRUCTURE} (cloned from {DSPL_STRUCTURE})")


# ── Bulk Salary Structure Assignment ──────────────────────────────

def _bulk_assign():
    employees = frappe.get_all(
        "Employee",
        filters={"status": "Active"},
        fields=["name", "employee_name", "company", "designation",
                "department", "date_of_joining"],
    )
    # SSA from_date can't be before the employee's joining date; default
    # to FY 26-27 start, fall back to joining date for late starters.
    from frappe.utils import getdate
    fy_start = getdate(EFFECTIVE_FROM)

    structure_for = {DSPL: DSPL_STRUCTURE, DCEPL: DCEPL_STRUCTURE}

    counts = {"created": 0, "already_assigned": 0,
              "directors_skipped": 0, "errors": 0,
              "from_bank": 0, "from_band": 0, "from_default": 0}

    for emp in employees:
        designation = (emp.designation or "").upper().strip()
        if designation in DIRECTOR_DESIGNATIONS:
            counts["directors_skipped"] += 1
            continue

        # Skip if employee already has any submitted SSA
        if frappe.db.exists("Salary Structure Assignment",
                            {"employee": emp.name, "docstatus": 1}):
            counts["already_assigned"] += 1
            continue

        structure = structure_for.get(emp.company)
        if not structure:
            counts["errors"] += 1
            frappe.log_error(f"No structure mapped for company {emp.company} (emp {emp.name})",
                             "SalaryStructure")
            continue

        base, source = _resolve_base(emp.employee_name, designation)
        counts[f"from_{source}"] += 1

        try:
            from_date = EFFECTIVE_FROM
            if emp.date_of_joining and getdate(emp.date_of_joining) > fy_start:
                from_date = str(emp.date_of_joining)
            ssa = frappe.new_doc("Salary Structure Assignment")
            ssa.employee = emp.name
            ssa.salary_structure = structure
            ssa.from_date = from_date
            ssa.base = base
            ssa.company = emp.company
            ssa.insert(ignore_permissions=True)
            ssa.submit()
            counts["created"] += 1
            if counts["created"] % 25 == 0:
                frappe.db.commit()
                print(f"  … {counts['created']} assignments committed")
        except Exception as e:
            counts["errors"] += 1
            frappe.log_error(
                f"SSA failed for {emp.name} ({emp.employee_name}): {str(e)[:200]}",
                "SalaryStructure",
            )

    return counts


# ── Base resolution ───────────────────────────────────────────────

def _resolve_base(employee_name, designation_upper):
    """Returns (base_amount_inr, source) where source ∈ {bank, band, default}.

    BANK_BASES keys are exact ERPNext employee_name strings, so the lookup
    is direct — no fuzzy matching needed."""
    if employee_name in BANK_BASES:
        return BANK_BASES[employee_name], "bank"

    if designation_upper in DESIGNATION_BAND:
        b = DESIGNATION_BAND[designation_upper]
        if b > 0:
            return b, "band"

    return DEFAULT_BASE, "default"
